### ISSUE TITLE
KERNEL_LOGGER_NAME define issue

### ISSUE THREAD

**Issue by randodev** [Microsoft/krabsetw#52] opened 2018-09-19 12:39 UTC
Hi! I'm using the NuGet 1.0.12 package, wrote a simple script just to import <krabs.hpp>, and get the following error:
`no suitable constructor exists to convert from "const char [17]" to "std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t>>"`

**in kt.hpp:100**

Am I doing anything wrong?

Thanks!

**Comment by zacbrown** [comment] 2018-09-19 13:58
Looks like you’re using ASCII string (char/std::string). Krabsetw only supports wide strings (wchar_t/std::wstring).

**Comment by randodev** [comment] 2018-09-19 14:03
I don't understand the reply. I'm not `using ASCII strings`. I only wrote the following:
```
int main()
{
    krabs::user_trace user;
    return 0;
}
```
and got the error. the error is in a **krabs file (kt.hpp).**

What should I change in Visual Studio?

**Comment by zacbrown** [comment] 2018-09-19 14:07
Can you post the VS project somewhere I can look at it?

**Comment by randodev** [comment] 2018-09-19 14:12
I'm figuring it out slowly. The problem is on this line
`return KERNEL_LOGGER_NAME;`
that define is in evntrace.h which depends on `Target Platform Version`

Tried both **8.1** and **10.0.17134.0**

Here is the shared project: https://github.com/randodev/TestETW

**Comment by zacbrown** [comment] 2018-09-21 02:11
Hi - which version of Visual Studio are you using? I wasn't able to reproduce the error with a clean project from Visual Studio 2017.

**Comment by randodev** [comment] 2018-09-21 06:44
Hi. It's `Microsoft Visual Studio Professional 2017 - 15.7.6`

**Comment by zacbrown** [comment] 2018-09-27 02:47
Thanks - I'm not able to reproduce an error with that one. Are you building x64?

I did find a separate error - but it's related to C++ 17 language issues that were fixed in a recent change. Package isn't created yet for it but I opened #53 for that work.

**Comment by swannman** [comment] 2018-11-11 21:49
@randodev please reopen if this still repros for you. Thanks!

**Closed by swannman** 2018-11-11 21:49 UTC
